# Backend extension configuration file
configuration:
  sys_backend:
    name: CMS Backend
    description: Adds most of the Backend functionality of the CMS
    folder: Backend
    type: System
    version: 0.0.1
    author:
      name: Radu Mogoș
      email: radu.mogos@pixelplant.ch
      web: www.pixelplant.ch