# News extension configuration file
configuration:
  sys_news:
    name: News extension
    description: Adds news functionality to the CMS
    folder: News
    type: Local
    version: 0.0.1
    author:
      name: Radu Mogoș
      email: radu.mogos@pixelplant.ch
      web: www.pixelplant.ch
    dependencies:
      # the system backend extension is required in order for the news extension to work
      sys_backend:
        version: 0.0.1